title: Viniverse
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
minima:
  skin: dark
header_pages:
  - about.md
  - portfolio.md
minima:
  social_links:
    twitter: VinicioMiguel
    github: ViniMig
